services:
  frontend:
    build:
      context: .
      target: runner
    environment:
      - APP_PASSWORD=${APP_PASSWORD}
      - CLINICA_API_KEY=${CLINICA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
